variables:
  - common_settings: &common_settings
      binary_cache: https://cache.nix.vdx.hu/private
      binary_cache_public_key: private:O0/Z0BQZpKKHQQES65u7xNfZF7eCZoz9RKJi191TGaM=
      binary_cache_token:
        from_secret: attic_token

when:
  - event: push
    branch: main
  - event: pull_request

pipeline:
  flake-check:
    image: git.vdx.hu/voidcontext/woodpecker-plugin-nix-attic:0.1.1
    settings:
      <<: *common_settings
      script: |
        attic login default $PLUGIN_BINARY_CACHE $PLUGIN_BINARY_CACHE_TOKEN
        nix flake check
        attic push private $(nix-store --query --requisites --include-outputs $(nix path-info --derivation .#checks))

        # Check examples
        for dir in examples/*; do
          cd $CI_WORKSPACE/$dir
          nix flake check
          attic push private $(nix-store --query --requisites --include-outputs $(nix path-info --derivation .#default))
        done

  formatting-check:
    image: git.vdx.hu/voidcontext/woodpecker-plugin-nix-attic:0.1.1
    settings:
      <<: *common_settings
      script: |
        nix develop -c alejandra . --check
